### ISSUE TITLE
Reset Running Total

### ISSUE THREAD

**Issue by hm-tam** [aaronreimann/gravityforms-running-total#1]
Hey there, 

Nice plugin. Is there a way to reset the running total? Is it stored in the SQL database?

**Comment by aaronreimann** [comment]
The plugin calculates the number and it is dynamically generated... meaning, it isn't stored and it can't be reset. 

I'm up for helping you though.

**Comment by hm-tam** [comment]
I see... I guess I could create another form. I just need to reset it one time. However, it'd be pretty cool if it had some kind of reset button. Your plugin saved me from a lot of hours of work, so thanks for making this available.

**Comment by hm-tam** [comment]
I figured it out. All I had to do was clear the entries in the backend.
